### PR TITLE
separate files for projections

### PR DESCRIPTION
**Pull request by derhuerst**
This PR introduces single files (e.g. `p/mercator.js`) for every projection. This makes bundle sizes smaller and allows to easily add more projections.

ccf50002beb834daeb89c6c3552bfb5dfa9285dd is a breaking change, so i bumped the version number to `0.6.0`.

### CODE REVIEW

**Comment by juliuste** [comment]
Wouldn't it be better (for usability) to move the projections to the main folder?

**Comment by derhuerst** [comment]
> Wouldn't it be better (for usability) to move the projections to the main folder?

It's a matter of taste. Since there's lots of meta files (readme, gitignore) and since there might easily be more projections in the future, I moved them into a directory.

**Comment by derhuerst** [comment]
bump. (:

I will adapt the location of the projections to your taste (imho it's good like it this). would really like to see `projections@0.6.0` being released, as [`geojson-svgify` depends on it](https://travis-ci.org/derhuerst/geojson-svgify/jobs/166903617).

**Comment by derhuerst** [comment]
bump.

**Pull request merged**
